version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./:/app/
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
